
<img src="img/viu_logo.png" width="200">

## 01MIAR - Estructuras de datos, +Pandas

![logo](img/python_logo.png)

*Ivan Fuertes / Andrés Pérez*

In [1]:
import pandas as pd
import numpy as np

# Operaciones en pandas

#### Búsqueda

In [2]:
rand_matrix = np.random.randint(6,size=(2,3))
frame = pd.DataFrame(rand_matrix , columns=list('ABC'))
display(frame)

   A  B  C
0  4  4  5
1  1  4  3

In [3]:
# buscando columnas (DataFrame como dic, busca en claves)
'A' in frame

True

In [4]:
# buscando valores
display(frame.isin([3,2])) # --> mask de respuesta (valores que son 3 o 2)

       A      B      C
0  False  False  False
1  False  False   True

In [5]:
# Contar el número de ocurrencias
print(frame.isin([5]).values.sum())
display(frame.isin([5])) #devuelve una mask con valores true si el elemento es 5
type(frame.isin([5]).values) # pandas es una capa alrededor de numpy

1

       A      B      C
0  False  False   True
1  False  False  False

numpy.ndarray

In [6]:
# Cuántos valores son >= 4
mask = frame >= 4
print(mask.values.sum())
display(mask)

4

       A     B      C
0   True  True   True
1  False  True  False

#### Ordenación

In [7]:
from random import shuffle

rand_matrix = np.random.randint(20,size=(5,4))

indices = list(range(5))
shuffle(indices) # mezcla indices

frame = pd.DataFrame(rand_matrix , columns=list('DACB'), index=indices)
display(frame)

   D   A   C   B
3  9   8  15  13
0  7  12   4   0
1  4   4   5  16
4  1  14   0  16
2  6   2   8  16

In [8]:
# ordenar por índice
display(frame.sort_index(ascending=True))
display(frame)

   D   A   C   B
0  7  12   4   0
1  4   4   5  16
2  6   2   8  16
3  9   8  15  13
4  1  14   0  16

   D   A   C   B
3  9   8  15  13
0  7  12   4   0
1  4   4   5  16
4  1  14   0  16
2  6   2   8  16

In [9]:
#ordenar por columna
display(frame.sort_index(axis=1, ascending=True))

    A   B   C  D
3   8  13  15  9
0  12   0   4  7
1   4  16   5  4
4  14  16   0  1
2   2  16   8  6

In [10]:
# ordenar filas por valor en columna
display(frame.sort_values(by='A', ascending=True))

   D   A   C   B
2  6   2   8  16
1  4   4   5  16
3  9   8  15  13
0  7  12   4   0
4  1  14   0  16

In [11]:
# ordenar columnas por valor en fila
display(frame.sort_values(by=1, axis=1, ascending=True))

   D   A   C   B
3  9   8  15  13
0  7  12   4   0
1  4   4   5  16
4  1  14   0  16
2  6   2   8  16

In [12]:
# ordenar por valor en columna y guardar cambios
frame.sort_values(by='A', ascending=False, inplace=True)
display(frame)

   D   A   C   B
4  1  14   0  16
0  7  12   4   0
3  9   8  15  13
1  4   4   5  16
2  6   2   8  16

#### Ranking
- Construir un ranking de valores

In [13]:
display(frame)

   D   A   C   B
4  1  14   0  16
0  7  12   4   0
3  9   8  15  13
1  4   4   5  16
2  6   2   8  16

In [14]:
display(frame.rank(method='average'))

     D    A    C    B
4  1.0  5.0  1.0  4.0
0  4.0  4.0  2.0  1.0
3  5.0  3.0  5.0  2.0
1  2.0  2.0  3.0  4.0
2  3.0  1.0  4.0  4.0

In [15]:
# Imprimir, uno a uno, los valores de la columna 'C' de mayor a menor
for x in frame.sort_values(by='C', ascending=False)['C'].values:
    print(x)

15
8
5
4
0

# Operaciones

Operaciones matemáticas entre objetos

In [16]:
matrixA = np.random.randint(100,size=(4,4))
matrixB = np.random.randint(100,size=(4,4))
frameA = pd.DataFrame(matrixA)
frameB = pd.DataFrame(matrixB)
display(frameA)
display(frameB)

    0   1   2   3
0  97   7  65  74
1  27  78   8   6
2   5  56  99  98
3  86  63   0  71

    0   1   2   3
0  63   8  32  19
1  73  79  88  30
2  45  62  84  61
3  29  21  21  90

In [17]:
# a través de métodos u operadores
display(frameA + frameB == frameA.add(frameB))
display(frameA + frameB)

      0     1     2     3
0  True  True  True  True
1  True  True  True  True
2  True  True  True  True
3  True  True  True  True

     0    1    2    3
0  160   15   97   93
1  100  157   96   36
2   50  118  183  159
3  115   84   21  161

In [18]:
display(frameB - frameA == frameB.sub(frameA))
display(frameB - frameA)

      0     1     2     3
0  True  True  True  True
1  True  True  True  True
2  True  True  True  True
3  True  True  True  True

    0   1   2   3
0 -34   1 -33 -55
1  46   1  80  24
2  40   6 -15 -37
3 -57 -42  21  19

In [19]:
# si los frames no son iguales, valor por defecto NaN
frameC = pd.DataFrame(np.random.randint(100,size=(3,3)))
display(frameA)
display(frameC)
display(frameA + frameC)

    0   1   2   3
0  97   7  65  74
1  27  78   8   6
2   5  56  99  98
3  86  63   0  71

    0   1   2
0  49  37   9
1   8  50  78
2  48   7  97

       0      1      2   3
0  146.0   44.0   74.0 NaN
1   35.0  128.0   86.0 NaN
2   53.0   63.0  196.0 NaN
3    NaN    NaN    NaN NaN

In [20]:
# se puede especificar el valor por defecto con el argumento fill_value
display(frameA.add(frameC, fill_value=0))

       0      1      2     3
0  146.0   44.0   74.0  74.0
1   35.0  128.0   86.0   6.0
2   53.0   63.0  196.0  98.0
3   86.0   63.0    0.0  71.0

Operadores aritméticos solo válidos en elementos aceptables

In [21]:
frameD = pd.DataFrame({0: ['a','b'],1:['d','f']})
display(frameD)
frameA - frameD

   0  1
0  a  d
1  b  f

TypeError: unsupported operand type(s) for -: 'int' and 'str'

Operaciones entre Series y DataFrames

In [57]:
rand_matrix = np.random.randint(10, size=(3, 4))
df = pd.DataFrame(rand_matrix , columns=list('ABCD'))
display(df)

display(df.iloc[0])
# uso común, averiguar la diferencia entre una fila y el resto
display(df - df.iloc[0])
display(df.sub(df.iloc[0], axis=1))
# Por columnas cómo se restaría
display(df.sub(df['A'], axis=0))

   A  B  C  D
0  7  6  4  7
1  7  5  0  3
2  9  4  4  4

A    7
B    6
C    4
D    7
Name: 0, dtype: int32

   A  B  C  D
0  0  0  0  0
1  0 -1 -4 -4
2  2 -2  0 -3

   A  B  C  D
0  0  0  0  0
1  0 -1 -4 -4
2  2 -2  0 -3

   A  B  C  D
0  0 -1 -3  0
1  0 -2 -7 -4
2  0 -5 -5 -5

pandas se basa en NumPy, np operadores binarios y unarios son aceptables 

| Tipo | Operación | Descripción |
|:---------|:-----|:-----|
| Unario | *abs* | Valor absoluto de cada elemento |
| | *sqrt* | Raíz cuadrada de cada elemento |
| | *exp* | e^x, siendo x cad elemento |
| | *log, log10, log2* | Logaritmos en distintas bases de cada elemento |
| | *sign* | Retorna el signo de cada elemento (-1 para negativo, 0 o 1 para positivo) |
| | *ceil* | Redondea cada elemento por arriba |
| | *floor* | Redondea cada elemento por abajo |
| | *isnan* | Retorna si cada elemento es Nan |
| | *cos, sin, tan* | Operaciones trigonométricas en cada elemento |
| | *arccos, arcsin, arctan* | Inversas de operaciones trigonométricas en cada elemento |
| Binario | *add* | Suma de dos arrays |
| | *substract* | Resta de dos arrays |
| | *multiply* | Multiplicación de dos arrays |
| | *divide* | División de dos arrays |
| | *maximum, minimum* | Retorna el valor máximo/mínimo de cada pareja de elementos |
| | *equal, not_equal* | Retorna la comparación (igual o no igual) de cada pareja de elementos |
| | *greater, greater_equal, less, less_equal* | Retorna la comparación (>, >=, <, <= respectivamente) de cada pareja de elementos |

Aplicación de funciones a medida con lambda

In [23]:
rand_matrix = np.random.randint(10, size=(3, 4))
frame = pd.DataFrame(rand_matrix , columns=list('ABCD'))
display(frame)
print(frame.apply(lambda x : x.max() - x.min())) # diferencia por columna

   A  B  C  D
0  4  4  0  8
1  8  5  0  0
2  1  1  0  8

A    7
B    4
C    0
D    8
dtype: int32

In [24]:
# diferencia entre min y max por fila (no columna)
rand_matrix = np.random.randint(10, size=(3, 4))
frame = pd.DataFrame(rand_matrix , columns=list('ABCD'))
display(frame)
print(frame.apply(lambda x : x.max() - x.min(), axis = 1)) # diferencia por fila

   A  B  C  D
0  3  4  7  3
1  3  2  7  0
2  9  5  4  3

0    4
1    7
2    6
dtype: int32

# Estadística descriptiva
- Análisis preliminar de los datos
- Para Series y DataFrame

| Operación | Descripción |
|:----------|:------------|
| count | Número de valores no NaN |
| describe | Conjunto de estadísticas sumarias|
| min, max | Valores mínimo y máximo |
| argmin, argmax | Índices posicionales del valor mínimo y máximo |
| idxmin, idxmax | Índices semánticos del valor mínimo y máximo |
| sum | Suma de los elementos |
| mean | Media de los elementos |
| median | Mediana de los elementos |
| mad | Desviación absoluta media del valor medio |
| var | Varianza de los elementos |
| std | Desviación estándar de los elementos |
| cumsum | Suma acumulada de los elementos |
| diff | Diferencia aritmética de los elementos |

In [25]:
diccionario = { "nombre" : ["Marisa","Laura","Manuel", "Carlos"], "edad" : [34,34,11, 30], 
               "puntos" : [98,12,98,np.nan], "genero": ["F", "F", "M", "M"] }
frame = pd.DataFrame(diccionario)
display(frame)
display(frame.describe()) # datos generales de elementos

   nombre  edad  puntos genero
0  Marisa    34    98.0      F
1   Laura    34    12.0      F
2  Manuel    11    98.0      M
3  Carlos    30     NaN      M

            edad     puntos
count   4.000000   3.000000
mean   27.250000  69.333333
std    10.996211  49.652123
min    11.000000  12.000000
25%    25.250000  55.000000
50%    32.000000  98.000000
75%    34.000000  98.000000
max    34.000000  98.000000

In [26]:
print(type(frame['edad']))

<class 'pandas.core.series.Series'>

In [27]:
# operadores básicos
# print(frame.sum())

display(frame)
print(frame.sum(axis=1, numeric_only=True))

   nombre  edad  puntos genero
0  Marisa    34    98.0      F
1   Laura    34    12.0      F
2  Manuel    11    98.0      M
3  Carlos    30     NaN      M

0    132.0
1     46.0
2    109.0
3     30.0
dtype: float64

In [28]:
frame.mean(numeric_only=True)

edad      27.250000
puntos    69.333333
dtype: float64

In [29]:
frame.cumsum()

                    nombre  edad  puntos genero
0                   Marisa    34    98.0      F
1              MarisaLaura    68   110.0     FF
2        MarisaLauraManuel    79   208.0    FFM
3  MarisaLauraManuelCarlos   109     NaN   FFMM

In [30]:
frame.count()

nombre    4
edad      4
puntos    3
genero    4
dtype: int64

In [31]:
frame['edad'].std()

10.996211468804457

In [32]:
frame['edad'].idxmax()

0

In [33]:
frame['puntos'].idxmin()

1

In [34]:
# frame con las filas con los valores maximos de una columna
print(frame['puntos'].max())
display(frame[frame['puntos'] == frame['puntos'].max()])

98.0

   nombre  edad  puntos genero
0  Marisa    34    98.0      F
2  Manuel    11    98.0      M

## Agregaciones

In [35]:
display(frame)
df = frame.groupby('genero').count()
display(df)

   nombre  edad  puntos genero
0  Marisa    34    98.0      F
1   Laura    34    12.0      F
2  Manuel    11    98.0      M
3  Carlos    30     NaN      M

        nombre  edad  puntos
genero
F            2     2       2
M            2     2       1

In [36]:
display(frame.groupby('genero').mean(numeric_only=True))

        edad  puntos
genero
F       34.0    55.0
M       20.5    98.0

In [37]:
display(frame.groupby('genero').max())

        nombre  edad  puntos
genero
F       Marisa    34    98.0
M       Manuel    30    98.0

In [38]:
# funciones de agregación de varias columnas para obtener distintos estadísticos
display(frame.groupby('genero')[['edad', 'puntos']].aggregate(['min', 'mean', 'max']))

       edad           puntos
        min  mean max    min  mean   max
genero
F        34  34.0  34   12.0  55.0  98.0
M        11  20.5  30   98.0  98.0  98.0

In [39]:
# Filtrado de los datos en el que el conjunto no supera una media determinada 
def media(x):
    return x["edad"].mean() > 30

display(frame)
frame.groupby('genero').filter(media)

   nombre  edad  puntos genero
0  Marisa    34    98.0      F
1   Laura    34    12.0      F
2  Manuel    11    98.0      M
3  Carlos    30     NaN      M

   nombre  edad  puntos genero
0  Marisa    34    98.0      F
1   Laura    34    12.0      F

## Correlaciones

pandas incluye métodos para analizar correlaciones
- Relación matemática entre dos variables (-1 negativamente relacionadas, 1 positivamente relacionadas, 0 sin relación)
- obj.corr(obj2) --> medida de correlación entre los datos de ambos objetos
- https://blogs.oracle.com/ai-and-datascience/post/introduction-to-correlation

### Ejemplo Fuel efficiency
- https://archive.ics.uci.edu/ml/datasets/Auto+MPG

In [40]:
import pandas as pd
path = 'http://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data'

mpg_data = pd.read_csv(path, delim_whitespace=True, header=None,
            names = ['mpg', 'cilindros', 'desplazamiento','potencia',
            'peso', 'aceleracion', 'año', 'origen', 'nombre'],
            na_values='?')

In [41]:
display(mpg_data.sample(5))

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion,año,origen,nombre
161,16.0,6,250.0,105.0,3897.0,18.5,75,1,chevroelt chevelle malibu
124,11.0,8,350.0,180.0,3664.0,11.0,73,1,oldsmobile omega
314,26.4,4,140.0,88.0,2870.0,18.1,80,1,ford fairmont
332,29.8,4,89.0,62.0,1845.0,15.3,80,2,vokswagen rabbit
36,19.0,6,250.0,88.0,3302.0,15.5,71,1,ford torino 500

In [42]:
display(mpg_data.describe(include='all'))

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion,año,origen,nombre
count,398.000000,398.000000,398.000000,392.000000,398.000000,398.000000,398.000000,398.000000,398
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,305
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ford pinto
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6
mean,23.514573,5.454774,193.425879,104.469388,2970.424623,15.568090,76.010050,1.572864,NaN
std,7.815984,1.701004,104.269838,38.491160,846.841774,2.757689,3.697627,0.802055,NaN
min,9.000000,3.000000,68.000000,46.000000,1613.000000,8.000000,70.000000,1.000000,NaN
25%,17.500000,4.000000,104.250000,75.000000,2223.750000,13.825000,73.000000,1.000000,NaN
50%,23.000000,4.000000,148.500000,93.500000,2803.500000,15.500000,76.000000,1.000000,NaN
75%,29.000000,8.000000,262.000000,126.000000,3608.000000,17.175000,79.000000,2.000000,NaN
max,46.600000,8.000000,455.000000,230.000000,5140.000000,24.800000,82.000000,3.000000,NaN

In [43]:
mpg_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   mpg             398 non-null    float64
 1   cilindros       398 non-null    int64
 2   desplazamiento  398 non-null    float64
 3   potencia        392 non-null    float64
 4   peso            398 non-null    float64
 5   aceleracion     398 non-null    float64
 6   año             398 non-null    int64
 7   origen          398 non-null    int64
 8   nombre          398 non-null    object
dtypes: float64(5), int64(3), object(1)
memory usage: 28.1+ KB

### Correlaciones entre valores

In [44]:
mpg_data['mpg'].corr(mpg_data['peso']) # + mpg = - peso

-0.8317409332443354

In [45]:
mpg_data['peso'].corr(mpg_data['aceleracion']) # + peso = - aceleracion

-0.41745731994039337

### Correlaciones entre todos los valores

In [46]:
mpg_data.corr(numeric_only=True)

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion,año,origen
mpg,1.000000,-0.775396,-0.804203,-0.778427,-0.831741,0.420289,0.579267,0.563450
cilindros,-0.775396,1.000000,0.950721,0.842983,0.896017,-0.505419,-0.348746,-0.562543
desplazamiento,-0.804203,0.950721,1.000000,0.897257,0.932824,-0.543684,-0.370164,-0.609409
potencia,-0.778427,0.842983,0.897257,1.000000,0.864538,-0.689196,-0.416361,-0.455171
peso,-0.831741,0.896017,0.932824,0.864538,1.000000,-0.417457,-0.306564,-0.581024
aceleracion,0.420289,-0.505419,-0.543684,-0.689196,-0.417457,1.000000,0.288137,0.205873
año,0.579267,-0.348746,-0.370164,-0.416361,-0.306564,0.288137,1.000000,0.180662
origen,0.563450,-0.562543,-0.609409,-0.455171,-0.581024,0.205873,0.180662,1.000000

In [47]:
#año y origen no parecen correlacionables
#eliminar columnas de la correlacion
corr_data = mpg_data.drop(['año','origen'],axis=1).corr(numeric_only=True)
display(corr_data)

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion
mpg,1.000000,-0.775396,-0.804203,-0.778427,-0.831741,0.420289
cilindros,-0.775396,1.000000,0.950721,0.842983,0.896017,-0.505419
desplazamiento,-0.804203,0.950721,1.000000,0.897257,0.932824,-0.543684
potencia,-0.778427,0.842983,0.897257,1.000000,0.864538,-0.689196
peso,-0.831741,0.896017,0.932824,0.864538,1.000000,-0.417457
aceleracion,0.420289,-0.505419,-0.543684,-0.689196,-0.417457,1.000000

In [48]:
# representación gráfica matplotlib
import matplotlib.pyplot as plt

In [49]:
# representación gráfica
corr_data.style.background_gradient(cmap=plt.get_cmap('RdYlGn'), axis=1)

In [50]:
# correlación más negativa
mpg_data.drop(['año','origen'],axis=1).corr(numeric_only=True).idxmin()

mpg                   peso
cilindros              mpg
desplazamiento         mpg
potencia               mpg
peso                   mpg
aceleracion       potencia
dtype: object

In [51]:
# correlación más positiva
mpg_data.drop(['año','origen'],axis=1).corr(numeric_only=True).idxmax()  #consigo misma....

mpg                          mpg
cilindros              cilindros
desplazamiento    desplazamiento
potencia                potencia
peso                        peso
aceleracion          aceleracion
dtype: object

In [52]:
# tabla similar con las correlaciones más positivas (evitar parejas del mismo valor)
positive_corr = mpg_data.drop(['año','origen'],axis=1).corr(numeric_only=True)
np.fill_diagonal(positive_corr.values, 0)
display(positive_corr)
positive_corr.idxmax()

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion
mpg,0.000000,-0.775396,-0.804203,-0.778427,-0.831741,0.420289
cilindros,-0.775396,0.000000,0.950721,0.842983,0.896017,-0.505419
desplazamiento,-0.804203,0.950721,0.000000,0.897257,0.932824,-0.543684
potencia,-0.778427,0.842983,0.897257,0.000000,0.864538,-0.689196
peso,-0.831741,0.896017,0.932824,0.864538,0.000000,-0.417457
aceleracion,0.420289,-0.505419,-0.543684,-0.689196,-0.417457,0.000000

mpg                  aceleracion
cilindros         desplazamiento
desplazamiento         cilindros
potencia          desplazamiento
peso              desplazamiento
aceleracion                  mpg
dtype: object

In [53]:
positive_corr.style.background_gradient(cmap=plt.get_cmap('RdYlGn'), axis=1, vmin=-1.0, vmax=1.0)

In [54]:
mpg_data

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion,año,origen,nombre
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150.0,3433.0,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140.0,3449.0,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790.0,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52.0,2130.0,24.6,82,2,vw pickup
395,32.0,4,135.0,84.0,2295.0,11.6,82,1,dodge rampage
396,28.0,4,120.0,79.0,2625.0,18.6,82,1,ford ranger
397,31.0,4,119.0,82.0,2720.0,19.4,82,1,chevy s-10

In [55]:
corr_data = mpg_data.loc[:,'mpg':'aceleracion']

## Ejercicios

- Ejercicios para practicar Pandas: https://github.com/ajcr/100-pandas-puzzles/blob/master/100-pandas-puzzles.ipynb
- Soluciones en: https://github.com/ajcr/100-pandas-puzzles/blob/master/100-pandas-puzzles-with-solutions.ipynb